const iconsMapping = {
 ".ts": "/icons/typescript.svg",
 ".tsx": "/icons/typescript.svg",
 ".js": "/icons/javascript.svg",
 ".jsx": "/icons/javascript.svg",
 ".json": "/icons/json.svg",
 ".html": "/icons/html.svg",
 ".css": "/icons/css.svg",
 ".scss": "/icons/sass.svg",
 ".sass": "/icons/sass.svg",
 ".less": "/icons/less.svg",
 ".graphql": "/icons/graphql.svg",
 ".md": "/icons/markdown.svg",
 ".mdx": "/icons/markdown.svg",
 ".vue": "/icons/vue.svg",
 ".php": "/icons/php.svg",
 ".py": "/icons/python.svg",
 ".rb": "/icons/ruby.svg",
 ".java": "/icons/java.svg",
 ".go": "/icons/go.svg",
 ".swift": "/icons/swift.svg",
 ".c": "/icons/c.svg",
 ".cpp": "/icons/cpp.svg",
 ".h": "/icons/h.svg",
 ".hpp": "/icons/hpp.svg",
 ".cs": "/icons/csharp.svg",
 ".edn": "/icons/clojure.svg",
 ".scala": "/icons/scala.svg",
 ".groovy": "/icons/groovy.svg",
 ".kt": "/icons/kotlin.svg",
 ".kts": "/icons/kotlin.svg",
 ".rs": "/icons/rust.svg",

 ".pdf": "/icons/pdf.svg",
};

export default iconsMapping;
